services:
  georoutegen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: georoutegen
    restart: unless-stopped

    ports:
      - "${PORT:-3000}:3000"

    environment:
      - PORT=3000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - DB_PATH=/app/data/georoute.db
      - NODE_ENV=production

    volumes:
      # 数据库持久化（系统级路径）
      - /var/lib/georoutegen:/app/data

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

    # 资源限制（可根据实际调整）
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
