name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          # 获取上一个 tag（如果存在）
          PREVIOUS_TAG=$(git tag --sort=-version:refname | grep -v "^${{ github.ref_name }}$" | head -n 1 || echo "")

          if [ -z "$PREVIOUS_TAG" ]; then
            # 如果没有上一个 tag，显示所有提交
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            # 显示从上一个 tag 到当前 tag 的提交
            CHANGELOG=$(git log ${PREVIOUS_TAG}..${{ github.ref_name }} --pretty=format:"- %s (%h)" --no-merges)
          fi

          # 保存到文件（处理多行）
          echo "$CHANGELOG" > changelog.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body: |
            ## Docker 镜像

            拉取镜像：
            ```bash
            docker pull ghcr.io/${{ github.repository_owner }}/georoutegen:${{ github.ref_name }}
            docker pull ghcr.io/${{ github.repository_owner }}/georoutegen:latest
            ```

            使用 docker-compose 部署：
            ```bash
            # 1. 克隆仓库
            git clone https://github.com/${{ github.repository }}.git
            cd GeoRouteGen

            # 2. 配置环境变量
            cp .env.example .env
            nano .env  # 修改 ADMIN_PASSWORD

            # 3. 准备数据库（如果还没有）
            sudo mkdir -p /var/lib/georoutegen
            sudo cp georoute.db /var/lib/georoutegen/

            # 4. 启动服务
            docker-compose up -d
            ```

            ## 更新日志

            查看 GitHub 自动生成的更新日志 ⬇️
